version: "1.0"

services:
    preprocessor:
        image: preprocessor
        depends_on:
            - ollama
        ports:
            - "8000:8000"
        volumes:
            - ~/.cache/datalab/models:/root/.cache/datalab/models
        restart: unless-stopped
        networks:
            - llm-net
        container_name: preprocessor

    ollama:
        image: ollama/ollama:0.9.0
        ports:
            - "11434:11434"
        volumes:
            - ~/models:/root/.ollama/models
        restart: unless-stopped
        networks:
            - llm-net
        container_name: ollama

    openwebui:
        image: ghcr.io/open-webui/open-webui:main
        ports:
            - "3030:3030"
        depends_on:
            - ollama
        restart: unless-stopped
        networks:
            - llm-net
        container_name: openwebui

    langfuse:
        image: ghcr.io/langfuse/langfuse:latest
        environment:
            - DATABASE_URL=postgresql://langfuse:langfuse@your-db-host:5432/langfuse
            - NEXTAUTH_SECRET=supersecret
            - NEXTAUTH_URL=http://localhost:3000
        ports:
            - "3000:3000"
        restart: unless-stopped
        networks:
            - llm-net
        container_name: langfuse

networks:
    llm-net: {}
